import unittest
import tempfile
from pathlib import Path

from bs4 import BeautifulSoup

from crawler import (
    build_local_image_path,
    IMAGE_PATH_PREFIX,
    looks_like_api_doc,
    looks_like_non_service,
    looks_like_unwanted_guide,
    url_to_output_path,
    extract_main_content,
    convert_html_to_markdown,
    LinkChecker,
)


class TestImagePaths(unittest.TestCase):
    """Test image path building functionality."""

    def test_build_local_image_path_places_asset_within_output(self):
        with tempfile.TemporaryDirectory() as tmp:
            output_root = Path(tmp) / "docs"
            image_path = "/images/deadline-cloud/latest/userguide/images/monitor-job-status.png"

            local_path = build_local_image_path(image_path, output_root)

            expected = output_root / "deadline-cloud/latest/userguide/images/monitor-job-status.png"
            self.assertEqual(local_path, expected)

    def test_build_local_image_path_rejects_missing_prefix(self):
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(ValueError):
                build_local_image_path("/assets/example.png", Path(tmp))

    def test_build_local_image_path_ignores_traversal(self):
        with tempfile.TemporaryDirectory() as tmp:
            image_path = f"{IMAGE_PATH_PREFIX}../deadline-cloud/./latest/userguide/images/example.png"

            local_path = build_local_image_path(image_path, Path(tmp))

            expected = Path(tmp) / "deadline-cloud/latest/userguide/images/example.png"
            self.assertEqual(local_path, expected)


class TestServiceFiltering(unittest.TestCase):
    """Test service and guide filtering functionality."""

    def test_looks_like_api_doc_detects_api_references(self):
        # Should detect API references
        self.assertTrue(looks_like_api_doc("APIReference"))
        self.assertTrue(looks_like_api_doc("api-reference"))
        self.assertTrue(looks_like_api_doc("apiref"))
        self.assertTrue(looks_like_api_doc("latest-api"))

        # Should not detect user guides
        self.assertFalse(looks_like_api_doc("userguide"))
        self.assertFalse(looks_like_api_doc("developerguide"))
        self.assertFalse(looks_like_api_doc("latest"))

    def test_looks_like_non_service_detects_sdks(self):
        # Should detect SDKs
        self.assertTrue(looks_like_non_service("sdk-for-python"))
        self.assertTrue(looks_like_non_service("sdk-for-java"))
        self.assertTrue(looks_like_non_service("python3"))
        self.assertTrue(looks_like_non_service("powershell"))
        self.assertTrue(looks_like_non_service("aws-toolkit"))
        self.assertTrue(looks_like_non_service("AWSJavaSDK"))
        self.assertTrue(looks_like_non_service("toolkit-for-vscode"))
        self.assertTrue(looks_like_non_service("prescriptive-guidance"))
        self.assertTrue(looks_like_non_service("solutions"))
        self.assertTrue(looks_like_non_service("freertos"))
        self.assertTrue(looks_like_non_service("code-library"))

        # Should not detect actual services
        self.assertFalse(looks_like_non_service("s3"))
        self.assertFalse(looks_like_non_service("ec2"))
        self.assertFalse(looks_like_non_service("deadline-cloud"))

    def test_looks_like_unwanted_guide_detects_autogenerated(self):
        # Should detect unwanted guide types
        self.assertTrue(looks_like_unwanted_guide("javadoc"))
        self.assertTrue(looks_like_unwanted_guide("site_map"))
        self.assertTrue(looks_like_unwanted_guide("cli"))

        # Should not detect legitimate guides
        self.assertFalse(looks_like_unwanted_guide("userguide"))
        self.assertFalse(looks_like_unwanted_guide("developerguide"))
        self.assertFalse(looks_like_unwanted_guide("getting-started"))


class TestUrlToOutputPath(unittest.TestCase):
    """Test URL to output path conversion."""

    def test_url_to_output_path_basic(self):
        url = "https://docs.aws.amazon.com/deadline-cloud/latest/userguide/what-is-deadline-cloud.html"
        output_root = Path("/tmp/docs")

        result = url_to_output_path(url, output_root)

        expected = output_root / "deadline-cloud/latest/userguide/what-is-deadline-cloud.md"
        self.assertEqual(result, expected)

    def test_url_to_output_path_index(self):
        url = "https://docs.aws.amazon.com/s3/latest/userguide/"
        output_root = Path("/tmp/docs")

        result = url_to_output_path(url, output_root)

        expected = output_root / "s3/latest/userguide.md"
        self.assertEqual(result, expected)

    def test_url_to_output_path_removes_html_extension(self):
        url = "https://docs.aws.amazon.com/ec2/latest/userguide/concepts.html"

        result = url_to_output_path(url)

        expected = Path("ec2/latest/userguide/concepts.md")
        self.assertEqual(result, expected)


class TestHtmlToMarkdownConversion(unittest.TestCase):
    """Test HTML to Markdown conversion with real AWS documentation patterns."""

    def test_extract_main_content_finds_awsdocs_content(self):
        html = """
        <html>
            <head><title>Test</title></head>
            <body>
                <nav>Navigation</nav>
                <div id="awsdocs-content">
                    <h1>Main Content</h1>
                    <p>This is the documentation.</p>
                </div>
                <footer>Footer</footer>
            </body>
        </html>
        """
        soup = BeautifulSoup(html, "html.parser")

        main = extract_main_content(soup)

        self.assertIn("Main Content", main.get_text())
        self.assertNotIn("Navigation", main.get_text())

    def test_convert_html_to_markdown_preserves_structure(self):
        html = """
        <h1>Amazon S3 Overview</h1>
        <p>Amazon Simple Storage Service (Amazon S3) is an object storage service.</p>
        <h2>Key Features</h2>
        <ul>
            <li>Durability</li>
            <li>Scalability</li>
            <li>Security</li>
        </ul>
        <pre><code>aws s3 cp myfile.txt s3://mybucket/</code></pre>
        """

        markdown = convert_html_to_markdown(html)

        self.assertIn("# Amazon S3 Overview", markdown)
        self.assertIn("## Key Features", markdown)
        self.assertIn("* Durability", markdown)
        self.assertIn("* Scalability", markdown)
        self.assertIn("```", markdown)
        self.assertIn("aws s3 cp myfile.txt s3://mybucket/", markdown)

    def test_convert_html_to_markdown_handles_tables(self):
        html = """
        <table>
            <tr><th>Service</th><th>Use Case</th></tr>
            <tr><td>S3</td><td>Object storage</td></tr>
            <tr><td>EC2</td><td>Compute instances</td></tr>
        </table>
        """

        markdown = convert_html_to_markdown(html)

        self.assertIn("|", markdown)
        self.assertIn("Service", markdown)
        self.assertIn("S3", markdown)
        self.assertIn("Object storage", markdown)

    def test_convert_html_to_markdown_handles_complex_tables_with_long_content(self):
        """Test table conversion with complex content similar to SimpleDB DataModel.md.

        This tests the fix for tables that have:
        - Multiple columns (8 in this case)
        - Some cells with long content
        - Empty cells
        - Content that should appear after the table

        The bug was that _reflow_markdown_tables would allow expected_pipe_count
        to increase based on malformed rows, causing incorrect table structure.
        """
        html = """
        <table>
            <tr>
                <th>ID</th>
                <th>Category</th>
                <th>Subcat.</th>
                <th>Name</th>
                <th>Color</th>
                <th>Size</th>
                <th>Make</th>
                <th>Model</th>
            </tr>
            <tr>
                <td>Item_01</td>
                <td>Clothes</td>
                <td>Sweater</td>
                <td>Cathair Sweater</td>
                <td>Siamese</td>
                <td>Small, Medium, Large</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Item_02</td>
                <td>Clothes</td>
                <td>Pants</td>
                <td>Designer Jeans</td>
                <td>Paisley Acid Wash</td>
                <td>30x32, 32x32, 32x34</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Item_03</td>
                <td>Clothes</td>
                <td>Pants</td>
                <td>Sweatpants</td>
                <td>Blue, Yellow, Pink</td>
                <td>Large</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Item_04</td>
                <td>Car Parts</td>
                <td>Engine</td>
                <td>Turbos</td>
                <td></td>
                <td></td>
                <td>Audi</td>
                <td>S4</td>
            </tr>
            <tr>
                <td>Item_05</td>
                <td>Car Parts</td>
                <td>Emissions</td>
                <td>02 Sensor</td>
                <td></td>
                <td></td>
                <td>Audi</td>
                <td>S4</td>
            </tr>
            <tr>
                <td>Item_06</td>
                <td>Motorcycle Parts</td>
                <td>Bodywork</td>
                <td>Fender Eliminator</td>
                <td>Blue</td>
                <td></td>
                <td>Yamaha</td>
                <td>R1</td>
            </tr>
            <tr>
                <td>Item_07</td>
                <td>Motorcycle Parts, Clothing</td>
                <td>Clothing</td>
                <td>Leather Pants</td>
                <td>Black</td>
                <td>Small, Medium, Large</td>
                <td></td>
                <td></td>
            </tr>
        </table>
        <p>Regardless of how you store your data, Amazon SimpleDB automatically indexes your data for quick and accurate retrieval.</p>
        """

        markdown = convert_html_to_markdown(html)

        # Verify table structure
        lines = markdown.strip().split("\n")
        table_lines = [line for line in lines if line.strip().startswith("|")]

        # All table rows should have the same number of pipes
        if table_lines:
            # Count pipes in header row (first table line)
            expected_pipes = table_lines[0].count("|")

            for i, line in enumerate(table_lines):
                # Skip separator rows (rows with only dashes and pipes)
                if all(c in "|-: \t" for c in line):
                    continue

                pipe_count = line.count("|")
                self.assertEqual(
                    pipe_count,
                    expected_pipes,
                    f"Row {i} has {pipe_count} pipes but expected {expected_pipes}: {line[:100]}"
                )

        # Verify content is present (note: underscores are escaped in markdown)
        self.assertIn("ID", markdown)
        self.assertIn("Category", markdown)
        self.assertTrue("Item_01" in markdown or "Item\\_01" in markdown)
        self.assertIn("Cathair Sweater", markdown)
        self.assertTrue("Item_07" in markdown or "Item\\_07" in markdown)
        self.assertIn("Leather Pants", markdown)

        # Verify that content after the table is not included in table rows
        self.assertIn("Regardless of how you store your data", markdown)

        # The paragraph should appear on its own line(s), not in a table row
        paragraph_line = None
        for line in lines:
            if "Regardless of how you store your data" in line:
                paragraph_line = line
                break

        self.assertIsNotNone(paragraph_line, "Paragraph should be present in output")
        # The paragraph should not start with a pipe (not be part of the table)
        self.assertFalse(
            paragraph_line.strip().startswith("|"),
            "Paragraph after table should not be part of a table row"
        )


class TestLinkChecker(unittest.TestCase):
    """Test URL link checking and filtering."""

    def test_link_checker_accepts_valid_docs_urls(self):
        checker = LinkChecker(allowed_prefixes=["/s3/latest/userguide/"])

        valid_urls = [
            "https://docs.aws.amazon.com/s3/latest/userguide/index.html",
            "https://docs.aws.amazon.com/s3/latest/userguide/getting-started.html",
            "https://docs.aws.amazon.com/s3/latest/userguide/",
        ]

        for url in valid_urls:
            with self.subTest(url=url):
                self.assertTrue(checker(url))

    def test_link_checker_rejects_images_and_pdfs(self):
        checker = LinkChecker()

        invalid_urls = [
            "https://docs.aws.amazon.com/images/example.png",
            "https://docs.aws.amazon.com/pdfs/s3/whitepaper.pdf",
            "https://docs.aws.amazon.com/assets/logo.svg",
        ]

        for url in invalid_urls:
            with self.subTest(url=url):
                self.assertFalse(checker(url))

    def test_link_checker_rejects_external_domains(self):
        checker = LinkChecker()

        external_urls = [
            "https://aws.amazon.com/s3/",
            "https://console.aws.amazon.com/s3/",
            "https://github.com/aws/aws-cli",
        ]

        for url in external_urls:
            with self.subTest(url=url):
                self.assertFalse(checker(url))

    def test_link_checker_respects_allowed_prefixes(self):
        checker = LinkChecker(allowed_prefixes=["/s3/latest/userguide/"])

        # Should accept URLs with the allowed prefix
        self.assertTrue(checker("https://docs.aws.amazon.com/s3/latest/userguide/index.html"))

        # Should reject URLs without the allowed prefix
        self.assertFalse(checker("https://docs.aws.amazon.com/ec2/latest/userguide/index.html"))


if __name__ == "__main__":
    unittest.main()
