import unittest
import tempfile
from pathlib import Path
from unittest.mock import Mock

from crawler import (
    looks_like_api_doc,
    looks_like_non_service,
    looks_like_unwanted_guide,
    url_to_output_path,
    url_to_markdown_url,
    AwsDocsCrawler,
    LinkChecker,
)


class TestServiceFiltering(unittest.TestCase):
    """Test service and guide filtering functionality."""

    def test_looks_like_api_doc_detects_api_references(self):
        # Should detect API references
        self.assertTrue(looks_like_api_doc("APIReference"))
        self.assertTrue(looks_like_api_doc("api-reference"))
        self.assertTrue(looks_like_api_doc("apiref"))
        self.assertTrue(looks_like_api_doc("latest-api"))

        # Should not detect user guides
        self.assertFalse(looks_like_api_doc("userguide"))
        self.assertFalse(looks_like_api_doc("developerguide"))
        self.assertFalse(looks_like_api_doc("latest"))

    def test_looks_like_non_service_detects_sdks(self):
        # Should detect SDKs
        self.assertTrue(looks_like_non_service("sdk-for-python"))
        self.assertTrue(looks_like_non_service("sdk-for-java"))
        self.assertTrue(looks_like_non_service("python3"))
        self.assertTrue(looks_like_non_service("powershell"))
        self.assertTrue(looks_like_non_service("aws-toolkit"))
        self.assertTrue(looks_like_non_service("AWSJavaSDK"))
        self.assertTrue(looks_like_non_service("toolkit-for-vscode"))
        self.assertTrue(looks_like_non_service("prescriptive-guidance"))
        self.assertTrue(looks_like_non_service("solutions"))
        self.assertTrue(looks_like_non_service("freertos"))
        self.assertTrue(looks_like_non_service("code-library"))

        # Should not detect actual services
        self.assertFalse(looks_like_non_service("s3"))
        self.assertFalse(looks_like_non_service("ec2"))
        self.assertFalse(looks_like_non_service("deadline-cloud"))

    def test_looks_like_unwanted_guide_detects_autogenerated(self):
        # Should detect unwanted guide types
        self.assertTrue(looks_like_unwanted_guide("javadoc"))
        self.assertTrue(looks_like_unwanted_guide("site_map"))
        self.assertTrue(looks_like_unwanted_guide("cli"))

        # Should not detect legitimate guides
        self.assertFalse(looks_like_unwanted_guide("userguide"))
        self.assertFalse(looks_like_unwanted_guide("developerguide"))
        self.assertFalse(looks_like_unwanted_guide("getting-started"))


class TestUrlToOutputPath(unittest.TestCase):
    """Test URL to output path conversion."""

    def test_url_to_output_path_basic(self):
        url = "https://docs.aws.amazon.com/deadline-cloud/latest/userguide/what-is-deadline-cloud.html"
        output_root = Path("/tmp/docs")

        result = url_to_output_path(url, output_root)

        expected = output_root / "deadline-cloud/latest/userguide/what-is-deadline-cloud.md"
        self.assertEqual(result, expected)

    def test_url_to_output_path_index(self):
        url = "https://docs.aws.amazon.com/s3/latest/userguide/"
        output_root = Path("/tmp/docs")

        result = url_to_output_path(url, output_root)

        expected = output_root / "s3/latest/userguide.md"
        self.assertEqual(result, expected)

    def test_url_to_output_path_removes_html_extension(self):
        url = "https://docs.aws.amazon.com/ec2/latest/userguide/concepts.html"

        result = url_to_output_path(url)

        expected = Path("ec2/latest/userguide/concepts.md")
        self.assertEqual(result, expected)

    def test_url_to_output_path_preserves_internal_dots(self):
        """Filenames with multiple dots must not collide.

        AWS docs use dotted filenames like Tagging.Operations.view.keyspace.html
        and Tagging.Operations.view.table.html.  These must map to distinct
        output files, not both collapse into Tagging.Operations.view.md.
        """
        output_root = Path("/tmp/docs")
        base = "https://docs.aws.amazon.com/keyspaces/latest/devguide/"

        result_a = url_to_output_path(base + "Tagging.Operations.view.keyspace.html", output_root)
        result_b = url_to_output_path(base + "Tagging.Operations.view.table.html", output_root)
        result_c = url_to_output_path(base + "Tagging.Operations.view.stream.html", output_root)

        self.assertNotEqual(result_a, result_b)
        self.assertNotEqual(result_b, result_c)
        self.assertEqual(
            result_a,
            output_root / "keyspaces/latest/devguide/Tagging.Operations.view.keyspace.md",
        )
        self.assertEqual(
            result_b,
            output_root / "keyspaces/latest/devguide/Tagging.Operations.view.table.md",
        )

    def test_url_to_output_path_two_dots(self):
        """A filename with exactly two dots (name.sub.html) must keep both."""
        url = "https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Endpoints.Creating.html"
        result = url_to_output_path(url)
        self.assertEqual(result, Path("dms/latest/userguide/CHAP_Endpoints.Creating.md"))

    def test_url_to_output_path_single_dot_unchanged(self):
        """A simple filename (one dot for .html) still works normally."""
        url = "https://docs.aws.amazon.com/s3/latest/userguide/Welcome.html"
        result = url_to_output_path(url)
        self.assertEqual(result, Path("s3/latest/userguide/Welcome.md"))

    def test_url_to_output_path_no_extension(self):
        """A URL with no .html extension gets .md appended."""
        url = "https://docs.aws.amazon.com/s3/latest/userguide/concepts"
        result = url_to_output_path(url)
        self.assertEqual(result, Path("s3/latest/userguide/concepts.md"))

    def test_url_to_output_path_many_dots(self):
        """Deeply dotted filenames preserve all segments."""
        url = "https://docs.aws.amazon.com/svc/latest/guide/A.B.C.D.E.html"
        result = url_to_output_path(url)
        self.assertEqual(result, Path("svc/latest/guide/A.B.C.D.E.md"))

    def test_url_to_output_path_dotted_siblings_unique(self):
        """Parent and child pages with shared dotted prefix don't collide."""
        base = "https://docs.aws.amazon.com/dms/latest/userguide/"
        parent = url_to_output_path(base + "CHAP_Tasks.html")
        child = url_to_output_path(base + "CHAP_Tasks.Creating.html")
        self.assertNotEqual(parent, child)
        self.assertEqual(parent, Path("dms/latest/userguide/CHAP_Tasks.md"))
        self.assertEqual(child, Path("dms/latest/userguide/CHAP_Tasks.Creating.md"))


class TestUrlToMarkdownUrl(unittest.TestCase):
    def test_replaces_html_extension(self):
        result = url_to_markdown_url(
            "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html"
        )

        self.assertEqual(
            result,
            "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.md",
        )

    def test_removes_query_and_fragment(self):
        result = url_to_markdown_url(
            "https://docs.aws.amazon.com/service/latest/guide/page.html?x=1#topic"
        )

        self.assertEqual(
            result,
            "https://docs.aws.amazon.com/service/latest/guide/page.md",
        )


class TestMarkdownDownload(unittest.TestCase):
    def test_process_url_downloads_aws_markdown_without_conversion(self):
        response = Mock()
        response.headers = {"Content-Type": "text/markdown; charset=utf-8"}
        response.text = "# AWS-authored Markdown\n\n<custom-element />\n"
        response.raise_for_status.return_value = None
        session = Mock()
        session.headers = {}
        session.get.return_value = response

        with tempfile.TemporaryDirectory() as tmp:
            output_dir = Path(tmp)
            crawler = AwsDocsCrawler(
                output_dir,
                session=session,
                requests_per_second=None,
            )
            crawler._link_checker = LinkChecker(
                ["/AmazonS3/latest/userguide/"]
            )
            page_url = (
                "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html"
            )

            crawler._process_url(page_url)

            session.get.assert_called_once_with(
                "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.md",
                timeout=30,
            )
            output = output_dir / "AmazonS3/latest/userguide/Welcome.md"
            self.assertEqual(output.read_text(), response.text)
            self.assertEqual(crawler.visited_urls, [page_url])


class TestLinkChecker(unittest.TestCase):
    """Test URL link checking and filtering."""

    def test_link_checker_accepts_valid_docs_urls(self):
        checker = LinkChecker(allowed_prefixes=["/s3/latest/userguide/"])

        valid_urls = [
            "https://docs.aws.amazon.com/s3/latest/userguide/index.html",
            "https://docs.aws.amazon.com/s3/latest/userguide/getting-started.html",
            "https://docs.aws.amazon.com/s3/latest/userguide/",
        ]

        for url in valid_urls:
            with self.subTest(url=url):
                self.assertTrue(checker(url))

    def test_link_checker_rejects_images_and_pdfs(self):
        checker = LinkChecker()

        invalid_urls = [
            "https://docs.aws.amazon.com/images/example.png",
            "https://docs.aws.amazon.com/pdfs/s3/whitepaper.pdf",
            "https://docs.aws.amazon.com/assets/logo.svg",
        ]

        for url in invalid_urls:
            with self.subTest(url=url):
                self.assertFalse(checker(url))

    def test_link_checker_rejects_external_domains(self):
        checker = LinkChecker()

        external_urls = [
            "https://aws.amazon.com/s3/",
            "https://console.aws.amazon.com/s3/",
            "https://github.com/aws/aws-cli",
        ]

        for url in external_urls:
            with self.subTest(url=url):
                self.assertFalse(checker(url))

    def test_link_checker_respects_allowed_prefixes(self):
        checker = LinkChecker(allowed_prefixes=["/s3/latest/userguide/"])

        # Should accept URLs with the allowed prefix
        self.assertTrue(checker("https://docs.aws.amazon.com/s3/latest/userguide/index.html"))

        # Should reject URLs without the allowed prefix
        self.assertFalse(checker("https://docs.aws.amazon.com/ec2/latest/userguide/index.html"))


if __name__ == "__main__":
    unittest.main()
